version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: tattooz_mysql 

    restart: unless-stopped

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tattoz_db
      MYSQL_USER: dias
      MYSQL_PASSWORD: dias

    ports:
      - "3306:3306"

    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: